config/routes.rb
Rails.application.routes.draw do

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :tasks
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/task.rb
class Task < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  before_action  :set_task, only: [:show, :edit, :update, :destroy]
  def index
    @tasks = Task.all
  end

  def show
  end

  def update
    @task.update(task_params)
    redirect_to tasks_path
  end

  def edit
  end

  def destroy
    @task.delete
    redirect_to tasks_path
  end

  def new
    @task = Task.new()
  end

  def create
    res = task_params.clone
    res[:percent] = 5
    @task = Task.new(res)
    @task.save
    redirect_to
  end
  private

  def set_task
    @task = Task.find(params[:id])
  end

  # These are 'strong params', Rails is asking us to 'whitelist'
  # all the params it will accept when assigning params to the
  # fields in a restaurant
  def task_params
    params.require(:task).permit(:title, :percent, :due_date)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsTaskManager</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/tasks/_task_form.html.erb
<%= form_for(@task) do |f| %>
  <%= f.label :title %>
  <%= f.text_field :title %>
  <%= f.label :percent %>
  <%= f.number_field :percent, in: 0...100 %>
  <%= f.label :due_date %>
  <%= f.date_field :due_date %>

  <%= f.submit %>
<% end %>

app/views/tasks/create.html.erb
<h1>Tasks#create</h1>
<p>Find me in app/views/tasks/create.html.erb</p>

app/views/tasks/delete.html.erb
<h1>Tasks#delete</h1>
<p>Find me in app/views/tasks/delete.html.erb</p>

app/views/tasks/edit.html.erb
<h1>Tasks#edit</h1>
<p>Find me in app/views/tasks/edit.html.erb</p>
<%= render 'task_form' %>

app/views/tasks/index.html.erb
<h1>Tasks#index</h1>
<p>Find me in app/views/tasks/index.html.erb</p>


<% @tasks.each do |t| %>
<p>
   <h2> <%=  t.id %> </h2>
</p><p>
   <h2> <%=  t.due_date %> </h2>

  </p>
<p>

<h2> percent : <%=  t.percent %> </h2>
</p>
 <%= link_to t.title, task_path(t) %>
 <% end %>

app/views/tasks/new.html.erb
<h1>Tasks#new</h1>
<p>Find me in app/views/tasks/new.html.erb</p>

<%= render 'task_form' %>

app/views/tasks/show.html.erb
<h1>Tasks#show</h1>
<p>Find me in app/views/tasks/show.html.erb</p>
<p> <%= @task.title %></p>
  <p> <%= @task.percent %></p>
    <p> <%=   @task.due_date.hour%></p>
    <p> <%=   @task.due_date.min%></p>
    <p> <%=   @task.due_date.year%></p>

  <%= link_to 'Remove', task_path(@task), method: :delete, data: { confirm: 'Are you sure bro?'} %>
  <%= link_to 'Edit', edit_task_path(@task) %>

app/views/tasks/update.html.erb
<h1>Tasks#update</h1>
<p>Find me in app/views/tasks/update.html.erb</p>